version: "3.3"

services:
  # app:
  #   container_name: app
  #   command: npm run start
  #   stdin_open: true
  #   # restart: always
  #   # env_file: ../env/production.env
  #   image: node-app
  #   build:
  #     context: ../
  #     dockerfile: ./docker/Dockerfile
  #   ports:
  #     - 8080:8000
  #     # - ['${PORT}:${PORT}']
  #   # links:
  #   #   - db
  #   depends_on:
  #     - db

  hono-db:
    container_name: hono-db
    # env_file: ../env/production.env
    image: "postgres:18-alpine"
    restart: "no"
    ports:
      - 4321:5432
      # - ${DB_PORT}:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST=${DB_HOST}
    volumes:
      - db_data:/var/lib/postgresql/data

  hono_redis:
    container_name: hono_redis
    image: redis:7-alpine
    restart: "no"
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  hono-redis-commander:
    container_name: hono-redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      REDIS_HOSTS: "local:hono_redis:6379"
    restart: "no"
    ports:
      - 8081:8081
    depends_on:
      - hono_redis

volumes:
  db_data:
  redis_data:
